export const allowedActions = [
    "ADD_CONTRIBUTION",
    "ADD_INVESTMENT",
    "LIST_PENDING_CONTRIBUTION_REQUESTS",
    "LIST_PENDING_INVESTMENT_REQUESTS",
    "LIST_MEMBERS",
    "LIST_EVENTS",
    "LIST_UPCOMING_EVENTS",
    "GET_TOTAL_BALANCE",
    "GET_ANALYTICS",
    "NO_ACTION"
  ];